# [default: false] Indicates whether to deploy a test attacker container called eve
eve: false

# [default: None] A domain name to append to challenge names to create their default common name
domain: 10.0.2.15

# [default: './challenges'] The directory which contains your challenges
# If the the path is relative, it will be relative to the generated docker-compose.yml file
challenges_directory: ./challenges

# [optional] Configuration for the registrar server. Set to `null` or `false` to disable
registrar:
    # [default: 3960] The exposed port for the registrar server
    port: 3960
    # [default: "default"] The docker network the registrar is connected to.
    # The network will be unmanaged by compose except for the default network
    network: default
    # [default: false] Whether to serve using TLS
    # If enabled, configure.py will set up a CA and certificates for the registrar
    tls_enabled: true
    # [default: false] Whether to enable TLS client verification
    # Only has an effect if tls_enabled is true
    tls_verify_client: true
    # [optional] Clients for whom certificates will be generated
    # Used in conbination with tls_verify_client to provide authentication
    # For each client in this list a certificate and key will be created in the registrar/certs directory
    tls_clients:
        - admin
        - www

# [required] Configurations for each challenge
challenges:
    # [required] An indiviual challenge config. The key is the challenge name
    # This should be a valid unix filename and preferably short
    wordpress:
        # [default: 1194] The exposed external port for this challenges OpenVPN server
        port: 2000
        # [required] The compose files to which define this challenge
        # Paths should be relative to the challenges directory
        files:
            - wordpress/docker-compose.yml
            - common/docker-compose.yml
        # [default: {domain}.{challenge name}] The commonname used for the OpenVPN's certificates
        # This should be the domain name or ip that directs to this challenge
        commonname: 10.0.2.15
        # [default: None] If set, the OpenVPN management interface will be opened on localhost and the given port
        openvpn_management_port: null
