version: "3"
services:

  webserver:
    image: webdevops/php-apache-dev
    restart: always
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8001:80"
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/