version: '2'

services:
  main:
    build: .
    container_name: p11-zeus
    restart: on-failure
    ports:
      - "51100:8000"
    network_mode: bridge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined