version: '3'
services:
  xmas_ctf:
    build:
      context: .
    working_dir: /home/ctf
    container_name: file
    ports:
      - "10002:31337"
    entrypoint: /etc/chall_init.sh
    #deploy:
    #  resources:
    #    limits:
    #      memory: 100M
