name:                pnghs
version:             0.1.0.0
github:              "DrimTuer/pnghs"
license:             BSD3
author:              "DrimTuer"
maintainer:          "drimtuer@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DrimTuer/pnghs#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- JuicyPixels

library:
  source-dirs: src

executables:
  pnghs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pnghs

tests:
  pnghs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pnghs
