version: '2.1'

services:
    mysqlword:
        build: ./mysql
        image: naumachia/mysqlword

    apacheword:
        build: ./apache
        image: naumachia/apacheword
        depends_on:
            - mysqlword


networks:
    default:
        internal: true
        ipam:
            driver: mini
