apiVersion: v1
kind: Service
metadata:
  name: zumbo-service
  labels:
    app: zumbo
    tier: frontend
spec:
  type: LoadBalancer
  ports:
      - port: 80
        targetPort: 5000
  selector:
    app: zumbo
    tier: frontend
