apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: zumbo-vault
    tier: backend
spec:
  ports:
      - port: 8080
        targetPort: 8080
  selector:
    app: zumbo-vault
    tier: backend
