apiVersion: v1
kind: Service
metadata:
  name: steel-mountain-interface
  labels:
    app: steel-mountain-interface
    group: steel-mountain
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: steel-mountain-interface
