# Define which containers to run
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: delphi-status
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: delphi-status
    spec:
      containers:
      - name: delphi-status
        image: gcr.io/bsides-sf-ctf-2017/delphi-status
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: no-api-access-please
            readOnly: true
      volumes:
        - name: no-api-access-please
          emptyDir: {}
