apiVersion: v1
kind: Service
metadata:
  name: delphi-status-service
  labels:
    app: delphi-status
spec:
  type: LoadBalancer
  ports:
      - port: 8080
        targetPort: 8080
  selector:
    # This should match the app name above
    app: delphi-status
