# [default: None] A domain name to append to challenge names to create their default common name
domain: naum.tamuctf.com

# [default: './challenges'] The directory which contains your challenges
# If the the path is relative, it will be relative to the generated docker-compose.yml file
challenges_directory: ./challenges

# [required] Configurations for each challenge
challenges:
    copper:
        port: 2000
        files:
            - copper/docker-compose.yml
    
    altf4:
        port: 2001
        files:
            - altf4/docker-compose.yml

    key_xchange:
        port: 2002
        files:
            - key_xchange/docker-compose.yml

    homework:
        port: 2003
        files:
            - homework/docker-compose.yml

    pwn6:
        port: 2005
        files:
            - pwn6/docker-compose.yml

    listen:
        port: 2007
        files:
            - listen/docker-compose.yml

    wordpress:
        port: 2008
        files:
            - Wordpress/docker-compose.yml

    calculator:
        port: 2009
        files:
            - calculator/docker-compose.yml

    clock:
        port: 2010
        files:
            - clock/docker-compose.yml

    dude:
        port: 2011
        files:
            - dude/docker-compose.yml
