# Define which containers to run
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: the-year-2000
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: the-year-2000
    spec:
      containers:
      - name: the-year-2000
        # This should be the same container tag as created by the Makefile
        image: gcr.io/bsides-sf-ctf-2017/the-year-2000
        ports:
          # This is the port that the container exposes
          - containerPort: 80
